# note: spring boot runs this automatically if you uncomment 'pring-boot-docker-compose` dependency in pom.xml
services:
    emailhog:
        image: 'mailhog/mailhog'
        ports:
            - 1025:1025
